// src/app/layout.js
import localFont from "next/font/local";
import Navbar from "../components/Navbar";
import MeteorBackground from "../components/MeteorBackground"; // Import MeteorBackground
import "../styles/globals.css"; // Import CSS global

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Zams Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar /> {/* Navbar tetap di atas animasi */}
        <main>{children}</main> {/* Konten halaman */}
      </body>
    </html>
  );
}
