// src/app/layout.js
import localFont from "next/font/local";
import Navbar from "../components/Navbar";
import ScrollToTop from "../components/ScrollToTop";
import LastUpdate from "../components/LastUpdate";
import MeteorBackground from "../components/MeteorBackground"; // Import MeteorBackground
import "../styles/globals.css"; // Import CSS global

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Zams Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ paddingTop: "60px" }}>
        {" "}
        {/* Sesuaikan padding-top */}
        <main>{children}</main>
        <ScrollToTop />
        <LastUpdate />
      </body>
    </html>
  );
}
